import { z } from 'zod';

export const JobSchema = z.object({
  id: z.string(),
  title: z.string(),
  company: z.string(),
  location: z.string(),
  country: z.string().optional(),
  salary: z.string(),
  salary_min: z.number().default(0),
  salary_max: z.number().default(0),
  is_commission_only: z.boolean().default(false),
  Contact_Email: z.string().optional(),
  WhatsApp_Number: z.string().optional(),
  Decision_Maker_Title: z.string().optional(),
  company_domain: z.string().optional(),
  matchScore: z.number().default(0),
  url: z.string(),
  description: z.string(),
  requirements: z.array(z.string()).default([]),
  source: z.string().default('Apify'),
  dateFound: z.string().default(() => new Date().toISOString()),
  hasSponsorship: z.boolean().default(false),
  hasFlightTicket: z.boolean().default(false),
  hasVisa: z.boolean().default(false),
  hasTicket: z.boolean().default(false),
  hasAccommodation: z.boolean().default(false),
  tier: z.enum(['PREMIER', 'VERIFIED']).default('VERIFIED'),
  hrContact: z.string().optional(),
  employerEmail: z.string().optional(),
  postedBy: z.string().optional(),
  status: z.enum(['pending_audit', 'live', 'flagged', 'vetted', 'verified', 'vetting_pending', 'pending']).default('pending_audit'),
  safetyScore: z.number().optional(),
  recommendation: z.string().optional(),
  isHighValue: z.boolean().optional(),
  isVetted: z.boolean().optional(),
  ticketIncluded: z.boolean().optional(),
  accommodationSecured: z.boolean().optional(),
  leadId: z.string().optional(),
  gpLeadId: z.string().optional(),
  lat: z.number().optional(),
  lng: z.number().optional(),
  positionName: z.string().optional(),
  sector: z.enum(['Professional', 'Blue-Collar', 'Other']).optional(),
  category: z.enum(['blue_collar', 'professional', 'service_domestic', 'general']).optional(),
  node: z.string().optional(),
  complianceStatus: z.enum(['High Risk', 'Verified', 'Pending Review']).default('Pending Review'),
});

export type ValidatedJob = z.infer<typeof JobSchema>;
